// content.js
module.exports = [
  "Week 1: Welcome, fighter! Learn the basic stance and keep your guard up at all times.",
  "Week 2: Light daily cardio – brisk walking, jogging, or jump rope.",
  "Week 3: Shadowboxing for 3 rounds daily to build coordination and flow.",
  "Week 4: Challenge week: train 5 days in a row, even short sessions count.",
  "Week 5: Focus on shoulder and hip mobility.",
  "Week 6: Technique over power. Clean strikes only.",
  "Week 7: Heavy bag work or controlled impact training.",
  "Week 8: Proper breathing during attacks and movement.",
  "Week 9: Simple combinations (jab–cross, basic kicks).",
  "Week 10: Footwork focus – movement wins fights.",

  "Week 11: General progress evaluation.",
  "Week 12: Functional strength using bodyweight exercises.",
  "Week 13: Control week – reduce volume, increase precision.",
  "Week 14: Reflex and reaction training.",
  "Week 15: Increase round duration.",
  "Week 16: Introduction to clinch control.",
  "Week 17: Build the disciplined fighter mindset.",
  "Week 18: Fighter nutrition – clean food and proper hydration.",
  "Week 19: Active defense: slips, blocks, and movement.",
  "Week 20: 5-month progress analysis.",

  "Week 21: Light, controlled sparring.",
  "Week 22: Managing adrenaline under pressure.",
  "Week 23: Increased bag and shadowboxing volume.",
  "Week 24: Flexibility and recovery focus.",
  "Week 25: Challenge: zero missed training sessions.",
  "Week 26: Halfway point – you are no longer a beginner.",
  "Week 27: Fight-specific cardio conditioning.",
  "Week 28: Advanced combinations and transitions.",
  "Week 29: Attack your weaknesses.",
  "Week 30: Fear control and mental discipline.",

  "Week 31: Increase sparring intensity.",
  "Week 32: Timing and distance management.",
  "Week 33: Strategy and opponent reading.",
  "Week 34: Speed and explosiveness training.",
  "Week 35: Active recovery week.",
  "Week 36: Performance-focused nutrition.",
  "Week 37: Core and rotational strength.",
  "Week 38: Fighting from angles.",
  "Week 39: Emotional control in combat.",
  "Week 40: 10-month performance review.",

  "Week 41: Maintain pace under pressure.",
  "Week 42: Defensive combinations.",
  "Week 43: Mental toughness training.",
  "Week 44: Explosive lower-body power.",
  "Week 45: Rapid adaptation skills.",
  "Week 46: Harder but intelligent sparring.",
  "Week 47: Deep recovery and regeneration.",
  "Week 48: Speed combined with precision.",
  "Week 49: Full breath control mastery.",
  "Week 50: One full year of discipline.",

  "Week 51: Build your personal fighting style.",
  "Week 52: Video analysis (real or imagined).",
  "Week 53: Explosive combination attacks.",
  "Week 54: Performing under fatigue.",
  "Week 55: Champion-level mindset.",
  "Week 56: Distance and range control.",
  "Week 57: Balance and stability training.",
  "Week 58: Adapting in chaos.",
  "Week 59: Strategic recovery.",
  "Week 60: 15-month progress evaluation.",

  "Week 61: High-intensity performance phase.",
  "Week 62: Clean strikes under pressure.",
  "Week 63: Rhythm and tempo mastery.",
  "Week 64: Extreme focus training.",
  "Week 65: Explosive strength development.",
  "Week 66: Tactical sparring sessions.",
  "Week 67: Mental recovery and reset.",
  "Week 68: Surgical precision training.",
  "Week 69: Calmness in chaos.",
  "Week 70: 18-month progress analysis.",

  "Week 71: Patience and control.",
  "Week 72: Your style takes clear shape.",
  "Week 73: Near-perfect execution.",
  "Week 74: Psychological dominance.",
  "Week 75: Constant pressure application.",
  "Week 76: Intelligent recovery management.",
  "Week 77: Instant adaptation.",
  "Week 78: Decisive finishing skills.",
  "Week 79: Cold, focused mind.",
  "Week 80: 20-month performance review.",

  "Week 81: Advanced-level fighter phase.",
  "Week 82: Full control of the fight.",
  "Week 83: Eliminate wasted movement.",
  "Week 84: Power combined with intelligence.",
  "Week 85: Respect the process.",
  "Week 86: Elite-level sparring.",
  "Week 87: Complete physical recovery.",
  "Week 88: Mental clarity and confidence.",
  "Week 89: Absolute consistency.",
  "Week 90: 22-month evaluation.",

  "Week 91: No shortcuts allowed.",
  "Week 92: Final refinements.",
  "Week 93: Mind and body in sync.",
  "Week 94: Total confidence.",
  "Week 95: Supreme control.",
  "Week 96: Veteran-level calm.",
  "Week 97: Final hard push.",
  "Week 98: Peak discipline.",
  "Week 99: Ultimate preparation.",
  "Week 100: CONGRATULATIONS! You are now a complete fighter."
];

